# Player Roles
BARBARIAN_START_HEALTH = 100
BARBARIAN_START_DAMAGE = 25
BARBARIAN_START_SPEED = 0

MAGE_START_HEALTH = 75
MAGE_START_DAMAGE = 25
MAGE_START_SPEED = 3

ROGUE_START_HEALTH = 50
ROGUE_START_DAMAGE = 25
ROGUE_START_SPEED = 7

# Enemies
SLIME_START_HEALTH = 50