BARBARIAN_START_HEALTH = 100
BARBARIAN_START_DAMAGE = 25
BARBARIAN_START_SPEED = 0

MAGE_START_HEALTH = 75
MAGE_START_DAMAGE = 25
MAGE__START_SPEED = 3

ROGUE_START_HEALTH = 50
ROGUE_START_DAMAGE = 25
ROGUE__START_SPEED = 7